---
---

<!-- Once I have done several tidy tuesdays, I can use this as a left side navigation par -->
<div class="row" style="margin-top: 20px">
<div class="col-sm-3">
<div class="list-group table-of-contents" style="min-width: 180px" data-spy="affix" data-offset-top="0">
<a class="list-group-item" href="#navbar">Navbar</a>
<a class="list-group-item" href="#buttons">Buttons</a>
<a class="list-group-item" href="#typography">Typography</a>
<a class="list-group-item" href="#tables">Tables</a>
<a class="list-group-item" href="#forms">Forms</a>
<a class="list-group-item" href="#navs">Navs</a>
<a class="list-group-item" href="#indicators">Indicators</a>
<a class="list-group-item" href="#progress-bars">Progress bars</a>
<a class="list-group-item" href="#containers">Containers</a>
<a class="list-group-item" href="#dialogs">Dialogs</a>
</div>
</div>

<div class="col-sm-9">
sdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sd
sdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sd
sdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sd
sdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sd
sdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sd
sdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sdsdifnweofij sdois djgoisjd foisdj foisd isod fisudv sdij vosdiv sodiv jsdoivj osdivj sd
</div>
</div>