---
title: Sudoku Solver
type: "website"
layout: "sudoku_solver"
draft: yes
date: "2019-07-02"
modified: "2019-07-03"
---


This is long term pet project of mine. The ultimate goal of the project is to create an R Shiny app which will take an user provided image of a sudoku puzzle, read the data from the image, solve the puzzle, and return the results. The project will be broken into its major component parts. In general, the purpose of the project is to showcase some of my practical R experience, as well as to learn how to do several new things with R along the way. As I see see it now there will be five main components of this project as follows. 

1. Write an algorithm to solve a provided sudoku puzzle
2. Write algorithms that will process sukodu puzzle image data
3. Create a model to predict whether a box in a sudoku puzzle is blank or a 1-9
4. Create a model to predict wheter an image is a sudoku puzzle or not
5. Create a sudoku solving shiny app which incorporates the above

I do anticipate this changing as I progress through the project and I will update this information as things progress. Here are some more details about what I plan to do for each component. 

### 1 - Solving Algorithm
The goal of this algorithm will be simply to take an unsolved sudoku puzzle, input as a 9x9 matrix, and iterate through various logical steps to solve the puzzle. Instead of using a brute force algorithm, I intend to employ a method which applies similar logic that I use in order to solve a puzzle. 

I will add details for the remaining steps in a future update. 